repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|rst)$
      - id: end-of-file-fixer
        exclude: \.(md|rst)$
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^(?!src/).*

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(?!src/).*

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        exclude: ^(?!src/).*

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^8.57.0
          - '@typescript-eslint/eslint-plugin@^7.0.0'
          - '@typescript-eslint/parser@^7.0.0'
          - eslint-plugin-import@^2.29.1
          - eslint-plugin-jsx-a11y@^6.8.0
          - eslint-plugin-node@^11.1.0
          - eslint-plugin-prettier@^5.1.0
          - eslint-plugin-security@^3.0.0
          - eslint-plugin-sonarjs@^1.0.0
          - eslint-config-prettier@^9.1.0
          - prettier@^3.2.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^(?!.*\.(js|jsx|ts|tsx|json|md)$).*

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs

